### PR TITLE
change package name

### PR DESCRIPTION
**Pull request by mgautam98**
@dnabanita7 this is what I was trying to say. Package name be gazel and only the repo title as our team name.
Please check if you are still able to build it

### CODE REVIEW

**Comment by mgautam98** [comment]
@Biswajitghosh98 can you check if the package is working fine after this. We need to sort it out before we do any other work. Please check ASAP.

**Comment by Biswajitghosh98** [comment]
On it @mgautam98

**Comment by Biswajitghosh98** [comment]
@mgautam98 I'm able to add the master correctly, but your pull seems to have errored.

**Comment by mgautam98** [comment]
okay I am closing it. I will generate a new package I will put your temp.jl in it you can sync it later

**Pull request closed without merging**
