### PR TITLE
add control

### PR DESCRIPTION
**Pull request by mgautam98**
Solves #16 
@dnabanita7  @Biswajitghosh98 
Initial Implementation
I could have regex work for julia so I could not get the display name. Will look for alternatives later

### CODE REVIEW

**Comment by dnabanita7** [comment]
@mgautam98 you can use [this](https://gist.github.com/dataPulverizer/23c8d992d351d7faf0ed1c1966605b10) or [this](https://github.com/JuliaLang/julia/blob/44fa15b1502a45eac76c9017af94332d4557b251/base/regex.jl#L83-L108) and [this](https://github.com/JuliaLang/julia/blob/44fa15b1502a45eac76c9017af94332d4557b251/base/regex.jl#L419-L432)

**Comment by dnabanita7** [comment]
You can use 
```
Pkg.clone("https://github.com/YOURREPONAME/gazel.jl.git")
Pkg.build("gazel")

```
since it is unregistered.

**Comment by mgautam98** [comment]
[This](https://github.com/JuliaLang/julia/blob/44fa15b1502a45eac76c9017af94332d4557b251/base/regex.jl#L83-L108) was not working for me

**Comment by mgautam98** [comment]
added the regex thanks @dnabanita7 it worked

**Comment by mgautam98** [comment]
@Biswajitghosh98  @dnabanita7 I think it is good to merge
Any comments/reviews before merge?

**Pull request merged**
